version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd $CODEBUILD_SRC_DIR/aws-cdk
      - npm ci

  pre_build:
    commands:
      - npx cdk bootstrap

  build:
    commands:
      - npx cdk synth FastifyApiTempleteSwagger

  post_build:
    commands:
      - npx cdk deploy FastifyApiTempleteSwagger --require-approval never