version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - npm ci

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/api
      - pwd
      - npm run lint
      - cd $CODEBUILD_SRC_DIR/aws-cdk
      - npx cdk bootstrap

  build:
    commands:
      - npx cdk synth FastifyApiTempleteApi

  post_build:
    commands:
      - npx cdk deploy FastifyApiTempleteApi --require-approval never
